name: Playground
options:
  bundleIdPrefix: dev.yolk
packages:
  Yolk:
    path: ../../../packages/swift
targets:
  Playground:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PlaygroundApp
      - path: Generated
    dependencies:
      - package: Yolk
    settings:
      base:
        INFOPLIST_FILE: PlaygroundApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.yolk.Playground
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.9
