import { ModuleSpec, MethodSpec } from "./parser"

export function generateSwift(spec: ModuleSpec): string {
  const lines: string[] = []

  lines.push(`// Generated by Yolk codegen — do not edit`)
  lines.push(`// Source: ${spec.name}Spec`)
  lines.push(`import Foundation`)
  lines.push(`import Yolk`)
  lines.push(``)

  if (spec.state) {
    lines.push(`/// State representation for the "${spec.name}" module.`)
    lines.push(`public struct ${spec.state.name}: Codable, Sendable, Equatable {`)
    for (const prop of spec.state.properties) {
      lines.push(`    public let ${prop.name}: ${tsTypeToSwift(prop.type, spec)}`)
    }
    lines.push(`}`)
    lines.push(``)
  }

  lines.push(`/// Swift protocol for the "${spec.name}" module.`)
  lines.push(`/// Implement this with a Swift \`actor\` for automatic thread safety.`)
  lines.push(`public protocol ${spec.name}Module: YolkModule {`)

  for (const method of spec.methods) {
    const swiftParams = method.params
      .map((p) => `${p.name}: ${tsTypeToSwift(p.type, spec)}`)
      .join(", ")
    const swiftReturn = tsTypeToSwift(method.returnType, spec)
    const throwsClause = "throws"
    lines.push(`    func ${method.name}(${swiftParams}) async ${throwsClause} -> ${swiftReturn}`)
  }

  lines.push(`}`)
  lines.push(``)
  lines.push(`/// Default \`handle\` dispatch — generated so you only implement domain methods.`)
  lines.push(`public extension ${spec.name}Module {`)
  lines.push(`    static var moduleName: String { "${spec.name}" }`)
  lines.push(``)
  lines.push(`    func handle(method: String, args: Data) async throws -> Data {`)
  lines.push(`        let argArray = (try YolkBin.decode(args) as? [Any?]) ?? []`)
  lines.push(`        switch method {`)

  for (const method of spec.methods) {
    lines.push(`        case "${method.name}":`)
    const extractions = method.params.map((p, i) =>
      `            let ${p.name} = ${extractSwift(p.type, i)}`
    )
    extractions.forEach((l) => lines.push(l))
    const callArgs = method.params.map((p) => `${p.name}: ${p.name}`).join(", ")
    if (method.returnType === "void") {
      lines.push(`            _ = try await ${method.name}(${callArgs})`)
      lines.push(`            return try YolkBin.encode(nil)`)
    } else {
      lines.push(`            let result = try await ${method.name}(${callArgs})`)
      lines.push(`            return try YolkBin.encode(${wrapSwiftResult(method.returnType, spec)})`)
    }
  }

  lines.push(`        default:`)
  lines.push(`            throw YolkError.runtimeError("Unknown method \\(method) on ${spec.name}")`)
  lines.push(`        }`)
  lines.push(`    }`)
  lines.push(`}`)

  return lines.join("\n")
}

// ── Type mapping ──────────────────────────────────────────────────────────────

function tsTypeToSwift(t: string, spec?: ModuleSpec): string {
  switch (t) {
    case "string":   return "String"
    case "number":   return "Double"
    case "boolean":  return "Bool"
    case "void":     return "Void"
    case "ArrayBuffer": return "Data"
    case "null":
    case "undefined": return "Any?"
    default:
      if (t.endsWith(" | null") || t.endsWith(" | undefined")) {
        return `${tsTypeToSwift(t.replace(/ \| (null|undefined)$/, ""), spec)}?`
      }
      if (spec?.state && t === spec.state.name) {
        return spec.state.name
      }
      return "Any?"
  }
}

function extractSwift(tsType: string, index: number): string {
  const access = `argArray[${index}]`
  switch (tsType) {
    case "string":  return `try { () throws -> String  in guard let v = ${access} as? String else { throw YolkError.runtimeError("Expected string at arg ${index}") }; return v }()`
    case "number":  return `try { () throws -> Double  in guard let v = ${access} as? Double else { throw YolkError.runtimeError("Expected number at arg ${index}") }; return v }()`
    case "boolean": return `try { () throws -> Bool    in guard let v = ${access} as? Bool else { throw YolkError.runtimeError("Expected boolean at arg ${index}") }; return v }()`
    case "ArrayBuffer": return `try { () throws -> Data    in guard let v = ${access} as? Data else { throw YolkError.runtimeError("Expected buffer at arg ${index}") }; return v }()`
    default:        return `${access}`
  }
}

function wrapSwiftResult(tsType: string, spec?: ModuleSpec): string {
  // YolkBin.encode accepts Any?, so we just pass the result.
  // We only need special handling for the generated state struct to make sure it's seen as a dictionary for TLV.
  if (spec?.state && tsType === spec.state.name) {
      // Actually, YolkBin handles Codable? No, it handles [String: Any?].
      // We should probably make YolkBin support Codable, but for now let's just return result.
      return "result"
  }
  return "result"
}
