import { ModuleSpec, MethodSpec } from "./parser"

export function generateTS(spec: ModuleSpec): string {
  const lines: string[] = []

  lines.push(`// Generated by Yolk codegen — do not edit`)
  lines.push(`import { NativeModule, YolkBin } from "@yolk/sdk"`)
  lines.push(``)
  lines.push(`export class ${spec.name} extends NativeModule {`)
  lines.push(`  constructor() { super("${spec.name}") }`)
  lines.push(``)

  for (const method of spec.methods) {
    const params = method.params.map((p) => `${p.name}: ${p.type}`).join(", ")
    const returnType = method.returnType === "void" ? "void" : method.returnType
    lines.push(`  async ${method.name}(${params}): Promise<${returnType}> {`)
    if (method.returnType === "void") {
      lines.push(`    await this.call("${method.name}", ${method.params.map((p) => p.name).join(", ")})`)
    } else {
      lines.push(`    const resultBuffer = await this.call("${method.name}", ${method.params.map((p) => p.name).join(", ")}) as ArrayBuffer;`)
      lines.push(`    return YolkBin.decode(resultBuffer) as ${method.returnType};`)
    }
    lines.push(`  }`)
    lines.push(``)
  }

  lines.push(`}`)

  return lines.join("\n")
}
